# general
log: e
eager: False

# data params
corrp: True
corr: False
cat: False
nc: 8
nr: 8
nw: 0
pred: 0.7
weak_pred: 1.0
N: 1000

# model, other params
fields:
- auc
- acc
- wts_ent
- wts_l1
- g_ent
- f_g_ent
perturb_frac: 1.0
test_perturb_frac: 0.0
perturb_norm_bound: 0.0
perturb_norm_order: -1
std: False
epochs: 200
activation: sigmoid
batch_size: 20
adv_reg_lambda: 0.0
clean_pre_train: 0.0
lr: 0.01
l1_reg: 0.0
l2_reg: 0.0
optimizer: ftrl
multi_gpu: False

grid:
  l1_reg:
    - 0.0
    - 1.0
    - 10.0
    - 50.0
    - 100.0
    - 200.0
    - 400.0
    - 500.0

