# general
log: e
eager: False

# data params
corrp: True
corr: False
cat: False
nc: 8
nr: 0
nw: 20
pred: 0.7
weak_pred: 0.55
N: 1000


# model, other params
fields:
- auc
- acc
- wts_ent
- wts_l1
- wts_l1_linf
- wts_pct1pct
- g_ent
- f_g_ent
perturb_frac: 1.0
test_perturb_frac: 0.0
perturb_norm_order: -1
std: False
epochs: 200
activation: sigmoid
batch_size: 20
adv_reg_lambda: 0.0
clean_pre_train: 0.0
lr: 0.01
l1_reg: 0.0
l2_reg: 0.0
optimizer: sgd
multi_gpu: False

grid:
  perturb_norm_bound:
  - 0.0
  - 0.1
  - 0.5
  - 1.0
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 2.0
